### ISSUE TITLE
最新1.01版本不支持horizontal: true了

### ISSUE THREAD

**Issue by gascarrier** [maomiui/rime#118]
参考这里：https://github.com/rime/home/discussions/1576

需要在squirrel.custom.yaml里设置全局配置：
```
patch:
  show_notifications_when: appropriate     # 状态通知，可设为全开（always）全关（never）  
  style/candidate_list_layout: linear # linear | stack 在这里设置全局侯选词展示方式
  # 皮肤主题名称输入在下方，分为浅色和深色
  # 浅色主题
  style/color_scheme: wechat_light
  # 深色主题
  style/color_scheme_dark: wechat_dark
...
```
